# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=dmc

matrix:
  include:
    # Put these first because they supposedly take
    # more time to setup and are easy to fail.
    # Commenting these until https://github.com/japaric/cross/issues/110
    # is fixed.
    #- env: TARGET=asmjs-unknown-emscripten
    #- env: TARGET=asmjs-unknown-emscripten
    #  rust: nightly
    #- env: TARGET=wasm32-unknown-emscripten
    #- env: TARGET=wasm32-unknown-emscripten
    #  rust: nightly

    # Linux
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    # OSX
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # *BSD
    - env: TARGET=i686-unknown-freebsd
    - env: TARGET=x86_64-unknown-freebsd
    - env: TARGET=x86_64-unknown-netbsd

    # Other architectures
    #
    # Commenting Android targets because even though they're
    # supported, they fail at the end for obscure reasons.
    #- env: TARGET=arm-linux-androideabi
    #- env: TARGET=arm-linux-androideabi
    #  rust: nightly
    #- env: TARGET=armv7-linux-androideabi
    #- env: TARGET=armv7-linux-androideabi
    #  rust: nightly
    #- env: TARGET=aarch64-linux-android
    #- env: TARGET=aarch64-linux-android
    #  rust: nightly
    #
    #- env: TARGET=arm-unknown-linux-gnueabi
    #- env: TARGET=arm-unknown-linux-gnueabi
    #  rust: nightly
    # arm-unknown-linux-gnueabihf doesn't work with `cross`
    #- env: TARGET=arm-unknown-linux-gnueabihf
    #- env: TARGET=arm-unknown-linux-gnueabihf
    #  rust: nightly
    #- env: TARGET=armv7-unknown-linux-gnueabihf
    #- env: TARGET=armv7-unknown-linux-gnueabihf
    #  rust: nightly
    #- env: TARGET=aarch64-unknown-linux-gnu
    #- env: TARGET=aarch64-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=mips-unknown-linux-gnu
    #- env: TARGET=mips-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=mips64-unknown-linux-gnuabi64
    #- env: TARGET=mips64-unknown-linux-gnuabi64
    #  rust: nightly
    #- env: TARGET=mips64el-unknown-linux-gnuabi64
    #- env: TARGET=mips64el-unknown-linux-gnuabi64
    #  rust: nightly
    #- env: TARGET=mipsel-unknown-linux-gnu
    #- env: TARGET=mipsel-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=powerpc-unknown-linux-gnu
    #- env: TARGET=powerpc-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=powerpc64-unknown-linux-gnu
    #- env: TARGET=powerpc64-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=powerpc64le-unknown-linux-gnu
    #- env: TARGET=powerpc64le-unknown-linux-gnu
    #  rust: nightly
    #- env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    #- env: TARGET=s390x-unknown-linux-gnu DISABLE_TESTS=1
    #  rust: nightly

addons:
  apt:
    packages:
      - libgl1-mesa-dev
      - libgl1-mesa-glx
      - mesa-utils
      - libx11-dev
      - libxcursor-dev
      - libxi-dev
      - libxinerama-dev
      - libxrandr-dev
      - libxrender-dev
      - libxmu-dev
      - libxv-dev
      - xserver-xorg-video-dummy
      - xpra
      - xorg-dev
      - libudev-dev
      - libevdev-dev

before_install:
  - set -e
  - sudo add-apt-repository -y ppa:oibaf/graphics-drivers
  - sudo apt-get update -qq -y
  - export DEBIAN_FRONTEND=noninteractive
  - sudo apt-get -yq --force-yes install libgl1-mesa-dev libgl1-mesa-glx mesa-common-dev libglapi-mesa libgbm1 libgl1-mesa-dri libxatracker-dev xvfb libwacom-dev

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

before_script:
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - xpra --xvfb="Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :99
  - sleep 3 
  - LIBGL_ALWAYS_SOFTWARE=1 glxinfo
  - glxinfo
  - cat ${HOME}/.xpra/xorg.log

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
