[package]
authors = ["Yoan Lecoq <yoanlecoq.io@gmail.com>"]
description = "(placeholder) Idiomatic replacement for SDL2.\nThe acronym originally stood for DirectMedia Crate."
documentation = "https://docs.rs/dmc"
keywords = ["sdl2", "window", "opengl"]
categories = [ "multimedia", "game-engines" ]
license = "MIT/Apache-2.0"
repository = "https://github.com/yoanlcq/dmc"
name = "dmc"
version = "0.1.0" # remember to update html_root_url
build = "build.rs"


[dependencies]
log = "0.3.8"
num-traits = "0.1.37"
uuid = "0.5"
libc = "0.2.26"
vek = { git = "https://github.com/yoanlcq/vek" }

[target.'cfg(any(target_os = "linux", target_os = "freebsd", target_os = "dragonfly", target_os = "openbsd", target_os = "netbsd"))'.dependencies.x11]
version = "2.15.0"
features = ["xlib", "glx"]
